version: '3'
services:
  platform:
    image: platform
    build: fake-data-platform
    container_name: platform
  # tests:
  #   image: tests
  #   build: .
  #   container_name: tests
  #   depends_on:
  #     - platform
  #   links:
  #     - platform
  #   command: >
  #     -v
  #     -s
  #     --platform http://platform:5000
  #     --run-id 11111111-aaaa-bbbb-cccc-123455555555
  cli1:
    image: burnham
    build: application
    container_name: cli1
    depends_on:
      - platform
    links:
      - platform
    environment:
      BURNHAM_PLATFORM_URL: http://platform:5000
      BURNHAM_VERBOSE: 1
      BURNHAM_TELEMETRY: 1
      BURNHAM_TEST_RUN: "11111111-aaaa-bbbb-cccc-123455555555"
      BURNHAM_TEST_NAME: "test_cli1"
      BURNHAM_SPORE_DRIVE: "tardigrade"
      BURNHAM_MISSION: "MISSION E: ONE JUMP, ONE METRIC ERROR"
  cli2:
    image: burnham
    build: application
    container_name: cli2
    depends_on:
      - platform
    links:
      - platform
    environment:
      BURNHAM_PLATFORM_URL: http://platform:5000
      BURNHAM_VERBOSE: 1
      BURNHAM_TELEMETRY: 1
      BURNHAM_TEST_RUN: "11111111-aaaa-bbbb-cccc-123455555555"
      BURNHAM_TEST_NAME: "test_cli1"
      BURNHAM_SPORE_DRIVE: "tardigrade-dna"
      BURNHAM_MISSION: "MISSION G: FIVE WARPS, FOUR JUMPS"
