version: '3'
services:
  platform:
    image: platform
    build: fake-data-platform
    container_name: platform
  cli1:
    image: burnham
    build: application
    container_name: cli1
    depends_on:
      - platform
    links:
      - platform
    environment:
      BURNHAM_PLATFORM_URL: http://platform:5000
      BURNHAM_VERBOSE: 1
      BURNHAM_TELEMETRY: 1
      BURNHAM_TEST_RUN: "11111111-aaaa-bbbb-cccc-123455555555"
      BURNHAM_TEST_NAME: "test_cli1"
      BURNHAM_SPORE_DRIVE: "tardigrade"
    command: >
      "MISSION G: FIVE WARPS, FOUR JUMPS"
      "MISSION C: ONE JUMP"
  cli2:
    image: burnham
    build: application
    container_name: cli2
    depends_on:
      - platform
    links:
      - platform
    environment:
      BURNHAM_PLATFORM_URL: http://platform:5000
      BURNHAM_VERBOSE: 1
      BURNHAM_TELEMETRY: 1
      BURNHAM_TEST_RUN: "11111111-aaaa-bbbb-cccc-123455555555"
      BURNHAM_TEST_NAME: "test_cli1"
      BURNHAM_SPORE_DRIVE: "tardigrade-dna"
    command: >
      "MISSION A: ONE WARP"
      "MISSION B: TWO WARPS"
      "MISSION D: TWO JUMPS"
      "MISSION E: ONE JUMP, ONE METRIC ERROR"
      "MISSION F: TWO WARPS, ONE JUMP"
      "MISSION G: FIVE WARPS, FOUR JUMPS"
  cli3:
    image: burnham
    build: application
    container_name: cli3
    depends_on:
      - platform
    links:
      - platform
    environment:
      BURNHAM_PLATFORM_URL: http://platform:5000
      BURNHAM_VERBOSE: 1
      BURNHAM_TELEMETRY: 1
      BURNHAM_TEST_RUN: "11111111-aaaa-bbbb-cccc-123455555555"
      BURNHAM_TEST_NAME: "test_cli1"
    command: >
      "MISSION A: ONE WARP"
      "MISSION B: TWO WARPS"
