version: '3'
services:
  platform:
    image: platform
    build: fake-data-platform
    container_name: platform
  client1:
    image: burnham
    build: .
    container_name: client1
    depends_on:
      - platform
    links:
      - platform
    environment:
      BURNHAM_PLATFORM_URL: http://platform:5000
      BURNHAM_VERBOSE: 1
      BURNHAM_TELEMETRY: 1
      BURNHAM_TEST_RUN: "1234"
      BURNHAM_TEST_NAME: "test_space_travel"
      BURNHAM_EXPERIMENT: "time_travel"
      BURNHAM_EXPERIMENT_BRANCH: "wormhole"
  client2:
    image: burnham
    build: .
    container_name: client2
    depends_on:
      - platform
    links:
      - platform
    environment:
      BURNHAM_PLATFORM_URL: http://platform:5000
      BURNHAM_VERBOSE: 1
      BURNHAM_TELEMETRY: 0
      BURNHAM_TEST_RUN: "1234"
      BURNHAM_TEST_NAME: "test_space_travel"
