[bug]
color = "f78c6c"
name = "bug"
description = "Bugs and problems with burnham"

["code quality"]
color = "c792ea"
name = "code quality"
description = "Tasks related to linting, coding style, type checks"

["data platform"]
color = "80a4c2"
name = "data platform"
description = "Tasks related to the Data Platform work"

[dependencies]
color = "c792ea"
name = "dependencies"
description = "Tasks related to managing dependencies"

[discussion]
color = "ffeb95"
name = "discussion"
description = "Issues for discussing ideas for features"

["do not merge"]
color = "ef5350"
name = "do not merge"
description = "Pull requests which must not be merged"

[docker]
color = "cdebf7"
name = "docker"
description = "Tasks related to building Docker images"

[docs]
color = "21c7a8"
name = "docs"
description = "Tasks to write and update documentation"

[feature]
color = "82aaff"
name = "feature"
description = "New feature for burnham"

["good first issue"]
color = "7fdbca"
name = "good first issue"
description = "Good tasks for newcomers to burnham"

[misc]
color = "ecc48d"
name = "misc"
description = "Tasks that don't fit any of the other categories"

[project]
color = "d6deeb"
name = "project"
description = "Tasks related to managing this project"
