[CircleCI]
color = "ecc48d"
name = "CircleCI"
description = "Tasks related to managing CircleCI"

[Dependabot]
color = "ecc48d"
name = "Dependabot"
description = "Tasks related to managing Dependabot"

[GitHub]
color = "ecc48d"
name = "GitHub"
description = "Tasks related to managing GitHub"

[application]
color = "c792ea"
name = "application"
description = "Tasks related to the application component"

[bigquery]
color = "c792ea"
name = "bigquery"
description = "Tasks related to the bigquery component"

[bug]
color = "f78c6c"
name = "bug"
description = "Bugs and problems with burnham"

[capability]
color = "82aaff"
name = "capability"
description = "New capability for burnham or burnham-bigquery"

["code quality"]
color = "21c7a8"
name = "code quality"
description = "Tasks related to linting, coding style, type checks"

[dependencies]
color = "21c7a8"
name = "dependencies"
description = "Tasks related to managing dependencies"

[discussion]
color = "ffeb95"
name = "discussion"
description = "Issues for discussing ideas for features"

["do not merge"]
color = "ef5350"
name = "do not merge"
description = "Pull requests which must not be merged"

[docker]
color = "cdebf7"
name = "docker"
description = "Tasks related to building Docker images"

[docs]
color = "21c7a8"
name = "docs"
description = "Tasks to write and update documentation"

[fake-data-platform]
color = "c792ea"
name = "fake-data-platform"
description = "Tasks related to the fake-data-platform component"

[glean-sdk]
color = "80a4c2"
name = "glean-sdk"
description = "Issues and pull-requests related to the Glean SDK"

["good first issue"]
color = "7fdbca"
name = "good first issue"
description = "Good tasks for newcomers to burnham"

[misc]
color = "d6deeb"
name = "misc"
description = "Tasks that don't fit any of the other categories"

[project]
color = "d6deeb"
name = "project"
description = "Tasks related to managing this project"

[telemetry-airflow]
color = "80a4c2"
name = "telemetry-airflow"
description = "Issues and pull-requests related to Airflow"

["test scenario"]
color = "82aaff"
name = "test scenario"
description = "New end-to-end test scenario"
