version: 2.1

jobs:
  run_checks:
    docker:
    - image: python:3.7
    working_directory: ~/burnham/application
    steps:
    - checkout:
        path: ~/burnham/
    - run:
        name: Install tox
        command: |
          python -m pip install --upgrade pip
          python -m pip install tox
    - run:
        name: Run mypy
        command: |
          tox -e mypy
    - run:
        name: Run flake8
        command: |
          tox -e flake8
    - run:
        name: Run py37
        command: |
          tox -e py37

workflows:
  version: 2
  build:
    jobs:
    - run_checks